export const CANDIDATE_COMPOUND_MAPPINGS: Record<string, string> = {
  homegym: 'home gym',
  homedecor: 'home decor',
  smarthome: 'smart home',
  homeassistant: 'home assistant',
  homeschool: 'home school',
  homebase: 'home base',
  homekit: 'home kit',
  homefront: 'home front',
  hometown: 'home town',
  homecoming: 'home coming',
  homestead: 'home stead',
  farmhouse: 'farm house',
  babyproof: 'baby proof',
  weatherproof: 'weather proof',
  workout: 'work out',
  guestroom: 'guest room',
  livingroom: 'living room',
  diningroom: 'dining room',
  bedroom: 'bed room',
  bathroom: 'bath room',
  playroom: 'play room',
  mudroom: 'mud room',
  sunroom: 'sun room',
  laundryroom: 'laundry room',
  backyard: 'back yard',
  frontyard: 'front yard',
  doorlock: 'door lock',
  doorhandle: 'door handle',
  floorlamp: 'floor lamp',
  desklamp: 'desk lamp',
  tablelamp: 'table lamp',
  boxfan: 'box fan',
  towerfan: 'tower fan',
  airconditioner: 'air conditioner',
  toasteroven: 'toaster oven',
  robotvacuum: 'robot vacuum',
}

export const CANDIDATE_IRREGULAR_PLURALS: Record<string, string> = {
  // Add new irregular plurals here (e.g. 'oxen': 'ox')
}
