/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji'

export interface Config {
  auth: {
    users: UserAuthOperations
  }
  blocks: {}
  collections: {
    users: User
    media: Media
    posts: Post
    subscribers: Subscriber
    topics: Topic
    nodes: Node
    brands: Brand
    tags: Tag
    products: Product
    'product-scrapers': ProductScraper
    tasks: Task
    'ai-blocks': AiBlock
    'node-topics': NodeTopic
    'brand-topics': BrandTopic
    'aba-search-terms': AbaSearchTerm
    'search-term-asin-jobs': SearchTermAsinJob
    'ai-block-jobs': AiBlockJob
    'payload-kv': PayloadKv
    'payload-locked-documents': PayloadLockedDocument
    'payload-preferences': PayloadPreference
    'payload-migrations': PayloadMigration
  }
  collectionsJoins: {}
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>
    media: MediaSelect<false> | MediaSelect<true>
    posts: PostsSelect<false> | PostsSelect<true>
    subscribers: SubscribersSelect<false> | SubscribersSelect<true>
    topics: TopicsSelect<false> | TopicsSelect<true>
    nodes: NodesSelect<false> | NodesSelect<true>
    brands: BrandsSelect<false> | BrandsSelect<true>
    tags: TagsSelect<false> | TagsSelect<true>
    products: ProductsSelect<false> | ProductsSelect<true>
    'product-scrapers': ProductScrapersSelect<false> | ProductScrapersSelect<true>
    tasks: TasksSelect<false> | TasksSelect<true>
    'ai-blocks': AiBlocksSelect<false> | AiBlocksSelect<true>
    'node-topics': NodeTopicsSelect<false> | NodeTopicsSelect<true>
    'brand-topics': BrandTopicsSelect<false> | BrandTopicsSelect<true>
    'aba-search-terms': AbaSearchTermsSelect<false> | AbaSearchTermsSelect<true>
    'search-term-asin-jobs': SearchTermAsinJobsSelect<false> | SearchTermAsinJobsSelect<true>
    'ai-block-jobs': AiBlockJobsSelect<false> | AiBlockJobsSelect<true>
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>
    'payload-locked-documents':
      | PayloadLockedDocumentsSelect<false>
      | PayloadLockedDocumentsSelect<true>
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>
  }
  db: {
    defaultIDType: number
  }
  fallbackLocale: null
  globals: {}
  globalsSelect: {}
  locale: null
  user: User & {
    collection: 'users'
  }
  jobs: {
    tasks: unknown
    workflows: unknown
  }
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string
    password: string
  }
  login: {
    email: string
    password: string
  }
  registerFirstUser: {
    email: string
    password: string
  }
  unlock: {
    email: string
    password: string
  }
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number
  name: string
  /**
   * URL friendly identifier
   */
  slug: string
  avatar?: (number | null) | Media
  job_title?: string | null
  bio?: string | null
  updatedAt: string
  createdAt: string
  enableAPIKey?: boolean | null
  apiKey?: string | null
  apiKeyIndex?: string | null
  email: string
  resetPasswordToken?: string | null
  resetPasswordExpiration?: string | null
  salt?: string | null
  hash?: string | null
  loginAttempts?: number | null
  lockUntil?: string | null
  sessions?:
    | {
        id: string
        createdAt?: string | null
        expiresAt: string
      }[]
    | null
  password?: string | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number
  alt: string
  folder?: ('posts' | 'avatars' | 'others') | null
  updatedAt: string
  createdAt: string
  url?: string | null
  thumbnailURL?: string | null
  filename?: string | null
  mimeType?: string | null
  filesize?: number | null
  width?: number | null
  height?: number | null
  focalX?: number | null
  focalY?: number | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number
  title: string
  slug: string
  featured_media?: (number | null) | Media
  status?: ('draft' | 'published') | null
  silo?: ('gear' | 'stack' | 'ventures' | 'library') | null
  content_type?:
    | (
        | 'article'
        | 'directory'
        | 'workflow'
        | 'blueprint'
        | 'build-in-public'
        | 'download'
        | 'update'
      )
    | null
  /**
   * External link for directory entries or offsite resources.
   */
  external_url?: string | null
  /**
   * Direct download link if hosted externally.
   */
  download_url?: string | null
  /**
   * Upload a downloadable asset for library resources.
   */
  download_file?: (number | null) | Media
  meta_title?: string | null
  keywords?: string | null
  meta_description?: string | null
  authors?: (number | User)[] | null
  tags?: (number | Tag)[] | null
  excerpt?: string | null
  content?: {
    root: {
      type: string
      children: {
        type: any
        version: number
        [k: string]: unknown
      }[]
      direction: ('ltr' | 'rtl') | null
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | ''
      indent: number
      version: number
    }
    [k: string]: unknown
  } | null
  ai_status?:
    | (
        | 'pending'
        | 'processing_content'
        | 'processing_media'
        | 'content_completed'
        | 'media_completed'
        | 'completed'
      )
    | null
  published_at?: string | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number
  name: string
  slug: string
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers".
 */
export interface Subscriber {
  id: number
  email: string
  source?: string | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "topics".
 */
export interface Topic {
  id: number
  name: string
  display_name?: string | null
  slug: string
  active?: boolean | null
  /**
   * Must be reviewed before auto-publishing
   */
  requires_review?: boolean | null
  ai_status:
    | 'PENDING'
    | 'QUEUED'
    | 'METADATA_PROCESSING'
    | 'METADATA_COMPLETED'
    | 'METADATA_ERROR'
    | 'CONTENT_PROCESSING'
    | 'CONTENT_COMPLETED'
    | 'CONTENT_ERROR'
    | 'COMPLETED'
  /**
   * Click Share
   */
  click_share_sum?: number | null
  /**
   * Weighted Score
   */
  weighted_score_sum?: number | null
  alias?: string | null
  meta_title?: string | null
  meta_keywords?: string | null
  meta_description?: string | null
  excerpt?: string | null
  featured_media?: (number | null) | Media
  redirect?: boolean | null
  /**
   * Redirect URL, start with /
   */
  redirect_to?: string | null
  introductory?: {
    root: {
      type: string
      children: {
        type: any
        version: number
        [k: string]: unknown
      }[]
      direction: ('ltr' | 'rtl') | null
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | ''
      indent: number
      version: number
    }
    [k: string]: unknown
  } | null
  content?: {
    root: {
      type: string
      children: {
        type: any
        version: number
        [k: string]: unknown
      }[]
      direction: ('ltr' | 'rtl') | null
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | ''
      indent: number
      version: number
    }
    [k: string]: unknown
  } | null
  authors?: (number | User)[] | null
  tags?: (number | Tag)[] | null
  nodes_count?: number | null
  asin_count?: number | null
  /**
   * Conversion Share
   */
  conversion_share_sum?: number | null
  start_date?: string | null
  end_date?: string | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nodes".
 */
export interface Node {
  id: number
  /**
   * Unique node identifier
   */
  node_id: string
  /**
   * Display name for the node
   */
  display_name: string
  /**
   * Context-free name
   */
  context_free_name: string
  /**
   * Parent node identifier
   */
  parent?: string | null
  /**
   * Is root node
   */
  is_root?: boolean | null
  /**
   * Auto-generated slug (parent/current)
   */
  slug: string
  /**
   * Number of topics associated with this node
   */
  topics_count?: number | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands".
 */
export interface Brand {
  id: number
  name: string
  slug: string
  logo?: (number | null) | Media
  description?: string | null
  asin_count?: number | null
  topics_count?: number | null
  click_share_sum?: number | null
  conversion_share_sum?: number | null
  weighted_score_sum?: number | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number
  asin: string
  brand?: (number | null) | Brand
  active?: boolean | null
  image?: string | null
  paapi5?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  status: 'PENDING' | 'PROCESSING' | 'COMPLETED' | 'ERROR' | 'NOT_FOUND'
  message?: string | null
  completed_at?: string | null
  click_share_sum?: number | null
  conversion_share_sum?: number | null
  weighted_score_sum?: number | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-scrapers".
 */
export interface ProductScraper {
  id: number
  asin: string
  active?: boolean | null
  scraperMetadata?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  status: 'PENDING' | 'PROCESSING' | 'COMPLETED' | 'ERROR' | 'NOT_FOUND'
  message?: string | null
  completed_at?: string | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tasks".
 */
export interface Task {
  id: number
  keywords: string
  node_ids?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  status: 'PENDING' | 'PROCESSING' | 'COMPLETED' | 'ERROR'
  message?: string | null
  metadata?: string | null
  completed_at?: string | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-blocks".
 */
export interface AiBlock {
  id: number
  /**
   * The node this AI block belongs to
   */
  node?: (number | null) | Node
  /**
   * The title of this AI block
   */
  title: string
  /**
   * The prompt used to generate the metadata, support simple {{ key }} replacement.
   */
  prompt_metadata: string
  /**
   * The prompt used to generate the content
   */
  prompt_content: string
  active?: boolean | null
  authors: {
    relationTo: 'users'
    value: number | User
  }[]
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "node-topics".
 */
export interface NodeTopic {
  id: number
  node: number | Node
  topic: number | Topic
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brand-topics".
 */
export interface BrandTopic {
  id: number
  brand: number | Brand
  topic: number | Topic
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "aba-search-terms".
 */
export interface AbaSearchTerm {
  id: number
  keywords: string
  asin: string
  /**
   * Node IDs
   */
  node_ids?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  /**
   * Occurrences
   */
  occurrences?: number | null
  /**
   * Search Rank
   */
  search_rank?: number | null
  /**
   * Conversion Share
   */
  conversion_share?: number | null
  /**
   * Click Share
   */
  click_share?: number | null
  /**
   * Weighted Score
   */
  weighted_score?: number | null
  start_date?: string | null
  end_date?: string | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search-term-asin-jobs".
 */
export interface SearchTermAsinJob {
  id: number
  task: number | Task
  keywords: string
  /**
   * Node IDs for filtering
   */
  node_ids?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  offset: number
  limit: number
  /**
   * Total records in API response
   */
  total?: number | null
  status: 'PENDING' | 'PROCESSING' | 'COMPLETED' | 'ERROR'
  /**
   * Job response body
   */
  body?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  /**
   * Job message or error details
   */
  message?: string | null
  /**
   * Job completion time
   */
  completed_at?: string | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-block-jobs".
 */
export interface AiBlockJob {
  id: number
  topic: number | Topic
  ai_block: number | AiBlock
  type: 'metadata' | 'content'
  status: 'PENDING' | 'PROCESSING' | 'COMPLETED' | 'ERROR'
  data?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  /**
   * Error message or processing logs
   */
  message?: string | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number
  key: string
  data:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number
  document?:
    | ({
        relationTo: 'users'
        value: number | User
      } | null)
    | ({
        relationTo: 'media'
        value: number | Media
      } | null)
    | ({
        relationTo: 'posts'
        value: number | Post
      } | null)
    | ({
        relationTo: 'subscribers'
        value: number | Subscriber
      } | null)
    | ({
        relationTo: 'topics'
        value: number | Topic
      } | null)
    | ({
        relationTo: 'nodes'
        value: number | Node
      } | null)
    | ({
        relationTo: 'brands'
        value: number | Brand
      } | null)
    | ({
        relationTo: 'tags'
        value: number | Tag
      } | null)
    | ({
        relationTo: 'products'
        value: number | Product
      } | null)
    | ({
        relationTo: 'product-scrapers'
        value: number | ProductScraper
      } | null)
    | ({
        relationTo: 'tasks'
        value: number | Task
      } | null)
    | ({
        relationTo: 'ai-blocks'
        value: number | AiBlock
      } | null)
    | ({
        relationTo: 'node-topics'
        value: number | NodeTopic
      } | null)
    | ({
        relationTo: 'brand-topics'
        value: number | BrandTopic
      } | null)
    | ({
        relationTo: 'aba-search-terms'
        value: number | AbaSearchTerm
      } | null)
    | ({
        relationTo: 'search-term-asin-jobs'
        value: number | SearchTermAsinJob
      } | null)
    | ({
        relationTo: 'ai-block-jobs'
        value: number | AiBlockJob
      } | null)
  globalSlug?: string | null
  user: {
    relationTo: 'users'
    value: number | User
  }
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number
  user: {
    relationTo: 'users'
    value: number | User
  }
  key?: string | null
  value?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number
  name?: string | null
  batch?: number | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T
  slug?: T
  avatar?: T
  job_title?: T
  bio?: T
  updatedAt?: T
  createdAt?: T
  enableAPIKey?: T
  apiKey?: T
  apiKeyIndex?: T
  email?: T
  resetPasswordToken?: T
  resetPasswordExpiration?: T
  salt?: T
  hash?: T
  loginAttempts?: T
  lockUntil?: T
  sessions?:
    | T
    | {
        id?: T
        createdAt?: T
        expiresAt?: T
      }
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T
  folder?: T
  updatedAt?: T
  createdAt?: T
  url?: T
  thumbnailURL?: T
  filename?: T
  mimeType?: T
  filesize?: T
  width?: T
  height?: T
  focalX?: T
  focalY?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T
  slug?: T
  featured_media?: T
  status?: T
  silo?: T
  content_type?: T
  external_url?: T
  download_url?: T
  download_file?: T
  meta_title?: T
  keywords?: T
  meta_description?: T
  authors?: T
  tags?: T
  excerpt?: T
  content?: T
  ai_status?: T
  published_at?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers_select".
 */
export interface SubscribersSelect<T extends boolean = true> {
  email?: T
  source?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "topics_select".
 */
export interface TopicsSelect<T extends boolean = true> {
  name?: T
  display_name?: T
  slug?: T
  active?: T
  requires_review?: T
  ai_status?: T
  click_share_sum?: T
  weighted_score_sum?: T
  alias?: T
  meta_title?: T
  meta_keywords?: T
  meta_description?: T
  excerpt?: T
  featured_media?: T
  redirect?: T
  redirect_to?: T
  introductory?: T
  content?: T
  authors?: T
  tags?: T
  nodes_count?: T
  asin_count?: T
  conversion_share_sum?: T
  start_date?: T
  end_date?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nodes_select".
 */
export interface NodesSelect<T extends boolean = true> {
  node_id?: T
  display_name?: T
  context_free_name?: T
  parent?: T
  is_root?: T
  slug?: T
  topics_count?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands_select".
 */
export interface BrandsSelect<T extends boolean = true> {
  name?: T
  slug?: T
  logo?: T
  description?: T
  asin_count?: T
  topics_count?: T
  click_share_sum?: T
  conversion_share_sum?: T
  weighted_score_sum?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T
  slug?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  asin?: T
  brand?: T
  active?: T
  image?: T
  paapi5?: T
  status?: T
  message?: T
  completed_at?: T
  click_share_sum?: T
  conversion_share_sum?: T
  weighted_score_sum?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-scrapers_select".
 */
export interface ProductScrapersSelect<T extends boolean = true> {
  asin?: T
  active?: T
  scraperMetadata?: T
  status?: T
  message?: T
  completed_at?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tasks_select".
 */
export interface TasksSelect<T extends boolean = true> {
  keywords?: T
  node_ids?: T
  status?: T
  message?: T
  metadata?: T
  completed_at?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-blocks_select".
 */
export interface AiBlocksSelect<T extends boolean = true> {
  node?: T
  title?: T
  prompt_metadata?: T
  prompt_content?: T
  active?: T
  authors?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "node-topics_select".
 */
export interface NodeTopicsSelect<T extends boolean = true> {
  node?: T
  topic?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brand-topics_select".
 */
export interface BrandTopicsSelect<T extends boolean = true> {
  brand?: T
  topic?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "aba-search-terms_select".
 */
export interface AbaSearchTermsSelect<T extends boolean = true> {
  keywords?: T
  asin?: T
  node_ids?: T
  occurrences?: T
  search_rank?: T
  conversion_share?: T
  click_share?: T
  weighted_score?: T
  start_date?: T
  end_date?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search-term-asin-jobs_select".
 */
export interface SearchTermAsinJobsSelect<T extends boolean = true> {
  task?: T
  keywords?: T
  node_ids?: T
  offset?: T
  limit?: T
  total?: T
  status?: T
  body?: T
  message?: T
  completed_at?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-block-jobs_select".
 */
export interface AiBlockJobsSelect<T extends boolean = true> {
  topic?: T
  ai_block?: T
  type?: T
  status?: T
  data?: T
  message?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T
  data?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T
  globalSlug?: T
  user?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T
  key?: T
  value?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T
  batch?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown
}

declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}
